### ISSUE TITLE
Crash updating dynmap to latest version and second non alpha

### ISSUE THREAD

**Issue by elak93** [GTNewHorizons/GTNH-Web-Map#13]
Updating to latest dynmap mod version has caused this issue. I deleted every dynmap config and setting I could find as the new settings on the latest would let me rebuild my map list without too much hassle. Unfortunately deleting dynmap.cfg and the dynmap folder did not resolve the issue. Any help would be greatly appreciated as my chatgpt troubleshooting isn't getting me far.

[crash-2024-05-25_01.35.54-server.txt](https://github.com/GTNewHorizons/GTNH-Web-Map/files/15441068/crash-2024-05-25_01.35.54-server.txt)
[fml-server-3.log](https://github.com/GTNewHorizons/GTNH-Web-Map/files/15441069/fml-server-3.log)

**Comment by dvdmandt** [comment]
Should be fixed in 0.3.27 / 0.4-alpha-12.
