### ISSUE TITLE
[CRASH] Crash on +376 nightly on Singleplayer.

### ISSUE THREAD

**Issue by IcaroKaue** [GTNewHorizons/GTNH-Web-Map#8]
Hello. I tried to run the mod on singleplayer on a nightly version, but it crashed, with Dynmap being accused as the reason. Any help appreciated.

Here's the link to the crash -> https://mclo.gs/2VsnPJl

**Comment by dvdmandt** [comment]
This should be fixed in 0.3.22 / 0.4-alpha-7.
